version: '3'
services:
  db:
    image: mongo:latest
    container_name: blog-hub-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  server:
    build: ./server
    container_name: blog-hub-server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MONGODB_URI: mongodb://db:27017/blog-hub
    volumes:
      - ./server:/usr/src/app
    networks:
      - app-network
    expose:
      - "3030"

  web:
    build: ./web
    container_name: blog-hub-web
    ports:
      - "4000:3000"  # React uygulamasının kullanacağı port
    volumes:
      - ./web:/usr/src/app  # React uygulamasını Docker içine monte etme

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
