export const ROUTE_PATHS = {
  NAVBAR: '/',
  404: '/404',
  BLOG: '/blog',
  CHANGE_PASSWORD: '/change-password',
  DASHBOARD: '/dashboard',
  EDIT_PROFILE: '/edit-profile',
  EDITOR: '/editor',
  HOME: '/home',
  MANAGE_BLOGS: '/manage-blogs',
  NOTIFICATIONS: '/notifications',
  PROFOLE: '/profile',
  SEARCH: '/search',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
}